# ==============================================================
# DATOS DEL EQUIPO  (completar ANTES del primer commit de trabajo)
# Escriban nombre y apellido tal cual aparecen en lista.
# ==============================================================
integrante1.nombre= Bryan
integrante1.apellido=Mark
integrante1.cedula=8-1032-527

integrante2.nombre=Angel
integrante2.apellido=Diaz
integrante2.cedula=8-1047-925

# VERSION: sumen TODOS los digitos de las dos cedulas (ignoren letras y guiones).
#   suma PAR   -> version=A
#   suma IMPAR -> version=B
# Ejemplo: 8-123-456 y 4-777-100  -> 8+1+2+3+4+5+6 + 4+7+7+7+1+0+0 = 55 -> impar -> B
version=
